In [1]:
import torch
print(torch.__version__)

d:\1pytorch\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.12.0+cpu


In [2]:
import torch
x= torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [3]:
y=torch.tensor([[1,2],[3,4]])
z=torch.zeros(3,2)
a=torch.rand(3,2)
print(a)
print(a[1,1])
print(1+a)

tensor([[0.0816, 0.1451],
        [0.8831, 0.1675],
        [0.9255, 0.4076]])
tensor(0.1675)
tensor([[1.0816, 1.1451],
        [1.8831, 1.1675],
        [1.9255, 1.4076]])


In [4]:
import torch
#input
x=torch.tensor([1.,2.,3.,4.])
#output
y=torch.tensor([2.,4.,6.,8.])
#wrong guess for w and x
w=torch.tensor(0.0)
b=torch.tensor(0.0)

y_pred=w*x + b

loss=((y_pred-y)**2).mean()

print("pred", y_pred)
print("actual", y)
print("loss",loss)

pred tensor([0., 0., 0., 0.])
actual tensor([2., 4., 6., 8.])
loss tensor(30.)


NN modules and dataloader

In [ ]:
import torch
import torch.nn as nn
# nn.Linear(input_features, output_features)
# nn.Linear(3,1) 

# w=torch.tensor(0.0, requires_grad=True)

# class MyModel(nn.module):
   
#    def __init__(self):
#      super().__init__() 
